# Generated by Django 5.2.4 on 2025-08-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_thumbnails/'),
        ),
    ]
